### ISSUE TITLE
Send to Kindle email?

### ISSUE THREAD

**Issue by horieva** [GrakovNe/kindle-sideload#2]
Can you explain how it works? 

Thank you.

**Comment by GrakovNe** [comment]
Users can send FB2 files to the bot through Telegram. When it receives these files, the bot converts them into formats like ePub, making them compatible with Kindle. It might use external https://github.com/rupor-github/fb2converter tool

Users can also provide a configuration file if they want to personalize aspects like the book's styling and layout. This customization ensures the eBook meets their preferences.

To send the eBook to their Kindle device, users need to share their Kindle email address. This email address is associated with their Kindle device and is crucial for the "Send to Kindle" feature provided by Amazon.

The bot then uses SMTP to send the eBook from a specific email address to the user's Kindle email address. This initiates the process of delivering the eBook to the user's Kindle device through Amazon's services.

**Comment by horieva** [comment]
Thank you. It works well.
